(() => {
  'use strict';
  const C=()=>window.YappathonVoiceContext||{};
  const $=id=>document.getElementById(id);
  let timer=null,inviteUnsub=null,currentCallKey='';
  const ringing=new Set();
  function convo(){const c=C();if(c.currentConvoType==='channel'&&c.currentChannel)return{type:'channel',id:c.currentChannel,name:'#'+c.currentChannel,members:[]};if(c.currentConvoType==='dm'&&c.currentDmId){const d=c.dmCache?.[c.currentDmId];if(!d)return null;return{type:d.type==='group'?'group':'dm',id:c.currentDmId,name:d.name||null,members:Array.isArray(d.members)?d.members:[]}}return null}
  const callId=c=>(c.type==='channel'?'channel_':'call_')+c.id;
  function callOpen(){const p=$('voice-panel');return !!p&&!p.hidden}
  function styles(){if($('yappathon-call-stage-style'))return;const s=document.createElement('style');s.id='yappathon-call-stage-style';s.textContent=`#voice-panel,.voice-panel{display:none!important;visibility:hidden!important;pointer-events:none!important}.voice-dm-stage{position:absolute!important;left:0;right:0;top:56px;height:300px;z-index:30;background:linear-gradient(180deg,var(--bg-alt),var(--bg));border-bottom:1px solid var(--border);box-shadow:0 16px 45px rgba(0,0,0,.18);display:flex;flex-direction:column;overflow:hidden}.voice-dm-stage[hidden]{display:none!important}.voice-dm-stage-head{display:flex;align-items:center;gap:10px;padding:11px 16px;border-bottom:1px solid var(--border);background:var(--bg-alt)}.voice-dm-live{width:8px;height:8px;border-radius:50%;background:var(--online);box-shadow:0 0 12px var(--online)}.voice-dm-title{font-weight:800;font-size:13px}.voice-dm-sub{font-size:11px;color:var(--text-muted);margin-left:auto}.voice-dm-grid{flex:1;min-height:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px;padding:12px 16px;overflow:auto}.voice-dm-tile{position:relative;min-height:125px;border:1px solid var(--border);border-radius:14px;background:var(--bg-elevated);display:flex;align-items:center;justify-content:center;overflow:hidden;box-shadow:0 8px 28px rgba(0,0,0,.12)}.voice-dm-tile.me{border-color:var(--accent)}.voice-dm-tile.ringing{border-color:#f6c85f;animation:yappathonRing 1s ease-in-out infinite}@keyframes yappathonRing{0%,100%{box-shadow:0 0 0 0 rgba(246,200,95,.12)}50%{box-shadow:0 0 0 7px rgba(246,200,95,.22)}}.voice-dm-avatar{width:62px;height:62px;border-radius:50%;object-fit:cover;background:var(--accent);display:grid;place-items:center;color:#fff;font-weight:800;font-size:20px}.voice-dm-label{position:absolute;left:8px;bottom:8px;right:8px;display:flex;align-items:center;gap:6px;padding:5px 7px;border-radius:7px;background:rgba(0,0,0,.48);color:#fff;font-size:11px;font-weight:700}.voice-dm-status{margin-left:auto;color:#8ff0bd;font-size:10px}.voice-dm-status.ringing{color:#ffd36b}.voice-dm-controls{display:flex;align-items:center;justify-content:center;gap:8px;padding:9px 14px;border-top:1px solid var(--border);background:var(--bg-alt)}.voice-dm-control{width:40px;height:36px;border:1px solid var(--border);border-radius:10px;background:var(--bg-input);color:var(--text);font-size:15px;cursor:pointer}.voice-dm-control.leave{width:auto;padding:0 15px;background:var(--danger);border-color:var(--danger);color:#fff;font-size:12px;font-weight:800}.main.voice-dm-active .messages{padding-top:314px}@media(max-width:860px){.voice-dm-stage{top:52px;height:270px}.main.voice-dm-active .messages{padding-top:284px}}@media(max-width:600px){.voice-dm-stage{height:245px}.main.voice-dm-active .messages{padding-top:258px}.voice-dm-grid{gap:6px;padding:7px}.voice-dm-tile{min-height:88px}}`;document.head.appendChild(s)}
  function hideCorner(){const p=$('voice-panel');if(p){p.style.setProperty('display','none','important');p.style.setProperty('visibility','hidden','important');p.style.setProperty('pointer-events','none','important')}}
  function stage(){const main=document.querySelector('.main');if(!main)return null;let x=$('voice-dm-stage');if(!x){x=document.createElement('section');x.id='voice-dm-stage';x.className='voice-dm-stage';x.hidden=true;x.innerHTML='<div class="voice-dm-stage-head"><span class="voice-dm-live"></span><div class="voice-dm-title" id="voice-dm-title">Voice call</div><div class="voice-dm-sub" id="voice-dm-sub">Voice Connected</div></div><div class="voice-dm-grid" id="voice-dm-grid"></div><div class="voice-dm-controls"><button class="voice-dm-control" id="voice-dm-mute">🎙</button><button class="voice-dm-control" id="voice-dm-deafen">🔊</button><button class="voice-dm-control leave" id="voice-dm-leave">Leave Call</button></div>';main.appendChild(x);$('voice-dm-mute').onclick=()=>$('voice-mute')?.click();$('voice-dm-leave').onclick=()=>$('voice-leave')?.click();$('voice-dm-deafen').onclick=()=>{const a=[...document.querySelectorAll('audio[data-yv]')],m=!a.every(x=>x.muted);a.forEach(x=>x.muted=m);$('voice-dm-deafen').textContent=m?'🔇':'🔊'};}return x}
  function users(c){const me=C().currentUser?.uid;if(c.type==='channel')return[];return c.members.filter(x=>x!==me).map(uid=>C().userCache?.[uid]||{uid,username:'Member'})}
  function connected(){const out=new Set();document.querySelectorAll('#voice-people .voice-person strong').forEach(n=>{const name=n.textContent.trim().toLowerCase();for(const [uid,u] of Object.entries(C().userCache||{}))if((u.username||'').toLowerCase()===name)out.add(uid)});return out}
  function avatar(u){if(u?.photoBase64){const i=document.createElement('img');i.className='voice-dm-avatar';i.src=u.photoBase64;i.alt='';return i}const d=document.createElement('div');d.className='voice-dm-avatar';d.textContent=(u?.username||u?.name||'?').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return d}
  function tile(u,status,me=false){const t=document.createElement('div');t.className='voice-dm-tile'+(me?' me':'')+(status==='ringing'?' ringing':'');t.appendChild(avatar(u));const l=document.createElement('div');l.className='voice-dm-label';const n=document.createElement('span');n.textContent=me?(C().profile?.username||'You'):(u?.username||u?.name||'Member');const st=document.createElement('span');st.className='voice-dm-status'+(status==='ringing'?' ringing':'');st.textContent=status==='ringing'?'🔔 Ringing':status==='connected'?'Connected':'Waiting';l.append(n,st);t.appendChild(l);return t}
  async function watchInvites(c){if(c.type==='channel'||!C().db)return;const k=callId(c);if(k===currentCallKey&&inviteUnsub)return;if(inviteUnsub){inviteUnsub();inviteUnsub=null}currentCallKey=k;try{const{collection,onSnapshot}=await import('https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js');inviteUnsub=onSnapshot(collection(C().db,'voiceCalls',k,'invites'),snap=>{ringing.clear();snap.forEach(d=>{if(d.data()?.status==='ringing')ringing.add(d.id)});render()},()=>{})}catch(_){} }
  function render(){const s=stage(),c=convo(),g=$('voice-dm-grid');if(!s||!c||!callOpen()||!g)return;g.innerHTML='';g.appendChild(tile({username:C().profile?.username||'You',photoBase64:C().profile?.photoBase64},'connected',true));if(c.type==='channel'){const seen=new Set();$('voice-people')?.querySelectorAll('.voice-person').forEach(p=>{const name=p.querySelector('strong')?.textContent?.trim();if(!name||name.toLowerCase()===(C().profile?.username||'').toLowerCase())return;const match=Object.entries(C().userCache||{}).find(([,u])=>(u.username||'').toLowerCase()===name.toLowerCase());const uid=match?.[0]||name;if(!seen.has(uid)){seen.add(uid);g.appendChild(tile(match?.[1]||{username:name},'connected'))}})}else{const con=connected();users(c).forEach(u=>g.appendChild(tile(u,ringing.has(u.uid)?'ringing':con.has(u.uid)?'connected':'waiting')))}$('voice-dm-title').textContent=c.type==='channel'?`${c.name} Voice`:c.type==='group'?(c.name||'Group Voice'):'Voice Call';$('voice-dm-sub').textContent=c.type==='channel'?'Everyone can join':'Voice Connected'}
  function update(){styles();hideCorner();const s=stage(),c=convo();if(!s)return;const show=!!c&&callOpen();s.hidden=!show;document.querySelector('.main')?.classList.toggle('voice-dm-active',show);if(!show){if(inviteUnsub){inviteUnsub();inviteUnsub=null}currentCallKey='';ringing.clear();return}watchInvites(c);render()}
  function start(){if(timer)return;update();timer=setInterval(update,250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
