/* YAPPATHON in-chat call UI v4. Keeps the existing voice engine, removes its corner panel, and restores live ringing. */
(()=>{'use strict';const C=()=>window.YappathonVoiceContext||{};const $=id=>document.getElementById(id);let timer=null,inviteUnsub=null,currentCallKey='';const ringing=new Set();
function css(){if($('yap-call-v4-style'))return;const s=document.createElement('style');s.id='yap-call-v4-style';s.textContent=`#voice-panel,.voice-panel,#voiceOverlay,.voice-overlay{display:none!important!important;visibility:hidden!important;pointer-events:none!important}.voice-dm-stage{position:absolute!important;left:0;right:0;top:56px;height:300px;z-index:30;background:var(--bg-alt);border-bottom:1px solid var(--border);display:flex;flex-direction:column;overflow:hidden}.voice-dm-stage[hidden]{display:none!important}.voice-dm-grid{flex:1;display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px;padding:12px 16px;overflow:auto}.voice-dm-tile{position:relative;min-height:125px;border:1px solid var(--border);border-radius:14px;background:var(--bg-elevated);display:flex;align-items:center;justify-content:center;overflow:hidden}.voice-dm-tile.me{border-color:var(--accent)}.voice-dm-tile.ringing{border-color:#f6c85f;animation:yapRing 1s ease-in-out infinite}.voice-dm-status.ringing{color:#ffd36b;font-weight:800}.voice-dm-avatar{width:62px;height:62px;border-radius:50%;object-fit:cover;background:var(--accent)}.voice-dm-label{position:absolute;bottom:8px;left:8px;right:8px;padding:5px 7px;border-radius:7px;background:rgba(0,0,0,.5);color:#fff;font-size:11px;font-weight:700;display:flex;gap:6px}.voice-dm-status{margin-left:auto;color:#8ff0bd}@keyframes yapRing{0%,100%{box-shadow:0 0 0 0 rgba(246,200,95,.15)}50%{box-shadow:0 0 0 8px rgba(246,200,95,.28)}}`;document.head.appendChild(s)}
function hideCorner(){document.querySelectorAll('#voice-panel,.voice-panel,#voiceOverlay,.voice-overlay').forEach(e=>{e.style.setProperty('display','none','important');e.style.setProperty('visibility','hidden','important');e.style.setProperty('pointer-events','none','important')})}
function convo(){const c=C();if(c.currentConvoType==='channel'&&c.currentChannel)return{type:'channel',id:c.currentChannel,name:'#'+c.currentChannel,members:[]};if(c.currentConvoType==='dm'&&c.currentDmId){const d=c.dmCache?.[c.currentDmId];if(!d)return null;return{type:d.type==='group'?'group':'dm',id:c.currentDmId,name:d.name||null,members:Array.isArray(d.members)?d.members:[]}}return null}
const callId=c=>(c.type==='channel'?'channel_':'call_')+c.id;
function stage(){const main=document.querySelector('.main');if(!main)return null;let x=$('voice-dm-stage');if(!x){x=document.createElement('section');x.id='voice-dm-stage';x.className='voice-dm-stage';x.hidden=true;x.innerHTML='<div style="padding:11px 16px;border-bottom:1px solid var(--border);font-weight:800">📞 <span id="voice-dm-title">Voice Call</span><span id="voice-dm-sub" style="float:right;font-size:11px;opacity:.7">Connected</span></div><div class="voice-dm-grid" id="voice-dm-grid"></div><div style="display:flex;justify-content:center;gap:8px;padding:9px;border-top:1px solid var(--border)"><button id="voice-dm-mute">🎙</button><button id="voice-dm-deafen">🔊</button><button id="voice-dm-leave">Leave Call</button></div>';main.appendChild(x);$('voice-dm-mute').onclick=()=>$('voice-mute')?.click();$('voice-dm-leave').onclick=()=>$('voice-leave')?.click();$('voice-dm-deafen').onclick=()=>{const a=[...document.querySelectorAll('audio[data-yv]')],m=!a.every(x=>x.muted);a.forEach(x=>x.muted=m);$('voice-dm-deafen').textContent=m?'🔇':'🔊'}}return x}
function users(c){const me=C().currentUser?.uid;return c.members.filter(x=>x!==me).map(uid=>C().userCache?.[uid]||{uid,username:'Member'})}
function connected(){const out=new Set();document.querySelectorAll('#voice-people .voice-person strong').forEach(n=>{const name=n.textContent.trim().toLowerCase();for(const [uid,u] of Object.entries(C().userCache||{}))if((u.username||'').toLowerCase()===name)out.add(uid)});return out}
function avatar(u){if(u?.photoBase64){const i=document.createElement('img');i.className='voice-dm-avatar';i.src=u.photoBase64;return i}const d=document.createElement('div');d.className='voice-dm-avatar';d.textContent=(u?.username||'?').slice(0,2).toUpperCase();return d}
function tile(u,status,me=false){const t=document.createElement('div');t.className='voice-dm-tile'+(me?' me':'')+(status==='ringing'?' ringing':'');t.appendChild(avatar(u));const l=document.createElement('div');l.className='voice-dm-label';const n=document.createElement('span');n.textContent=me?(C().profile?.username||'You'):(u?.username||'Member');const st=document.createElement('span');st.className='voice-dm-status'+(status==='ringing'?' ringing':'');st.textContent=status==='ringing'?'🔔 Ringing':status==='connected'?'Connected':'Waiting';l.append(n,st);t.appendChild(l);return t}
async function watch(c){if(c.type==='channel'||!C().db)return;const k=callId(c);if(k===currentCallKey&&inviteUnsub)return;if(inviteUnsub)inviteUnsub();currentCallKey=k;try{const{collection,onSnapshot}=await import('https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js');inviteUnsub=onSnapshot(collection(C().db,'voiceCalls',k,'invites'),snap=>{ringing.clear();snap.forEach(d=>{if(d.data()?.status==='ringing')ringing.add(d.id)});render()},()=>{})}catch(e){}}
function render(){const s=stage(),c=convo(),g=$('voice-dm-grid');if(!s||!c||s.hidden||!g)return;g.innerHTML='';g.appendChild(tile({username:C().profile?.username||'You',photoBase64:C().profile?.photoBase64},'connected',true));const con=connected();if(c.type==='channel'){$('voice-people')?.querySelectorAll('.voice-person').forEach(p=>{const n=p.querySelector('strong')?.textContent?.trim();if(n&&n.toLowerCase()!==(C().profile?.username||'').toLowerCase())g.appendChild(tile({username:n},'connected'))})}else users(c).forEach(u=>g.appendChild(tile(u,ringing.has(u.uid)?'ringing':con.has(u.uid)?'connected':'waiting')));$('voice-dm-title').textContent=c.type==='channel'?`${c.name} Voice`:c.type==='group'?(c.name||'Group Voice'):'Voice Call'}
function update(){css();hideCorner();const s=stage(),c=convo(),p=$('voice-panel');const active=!!c&&!!p&&!p.hidden;if(!s)return;s.hidden=!active;if(!active){if(inviteUnsub){inviteUnsub();inviteUnsub=null}ringing.clear();currentCallKey='';return}watch(c);render()}
function start(){if(timer)return;update();timer=setInterval(update,300)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start()})();
