(() => {
'use strict';
const FS='https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const C=()=>window.YappathonVoiceContext||{}, $=id=>document.getElementById(id), uid=()=>C().currentUser?.uid||'', uname=()=>C().profile?.username||'Player';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let f,roomId=null,room=null,players=new Map(),stopRoom=null,stopPlayers=null,stopLobby=null;
let canvas=null,ctx=null,balls=[],turn=0,turnUid='',aiming=false,anim=false,raf=0,last=0,host=false;
const W=1000,H=520,R=11,POCKET=25,RAIL=.84,REST=.7,FRICTION=.991,RESTITUTION=.94;
const pockets=[[0,0],[W/2,0],[W,0],[0,H],[W/2,H],[W,H]],colors=['#FF7A33','#7C8CFF','#4FBE7B','#FF6F9F'];
async function fs(){if(!f)f=await import(FS);return f}function toast(m){C().toast?.(m,'info')}
function css(){if($('pool-multi-css'))return;const s=document.createElement('style');s.id='pool-multi-css';s.textContent=`#pool-multi{position:fixed;inset:0;z-index:1600;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(0,0,0,.72);backdrop-filter:blur(10px)}#pool-multi.open{display:flex}.pm-shell{width:min(1120px,100%);height:min(92vh,820px);background:var(--bg-elevated);border:1px solid var(--border);border-radius:20px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 100px var(--shadow)}.pm-head{display:flex;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid var(--border)}.pm-head h2{margin:0;font-size:18px}.pm-sp{flex:1}.pm-close{border:0;background:none;color:var(--text-muted);font-size:20px}.pm-body{flex:1;min-height:0;overflow:auto;padding:16px}.pm-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pm-card{background:var(--bg-alt);border:1px solid var(--border);border-radius:14px;padding:16px}.pm-card h3{margin:0 0 8px;font-size:15px}.pm-card p{margin:0 0 12px;color:var(--text-muted);font-size:12px;line-height:1.5}.pm-input{width:100%;background:var(--bg-input);border:1px solid var(--border);color:var(--text);padding:10px;border-radius:9px;font:inherit}.pm-list{display:grid;gap:7px;max-height:300px;overflow:auto}.pm-room{display:flex;align-items:center;gap:10px;padding:10px;border:1px solid var(--border);border-radius:10px;background:var(--bg-input)}.pm-room .meta{flex:1;min-width:0}.pm-room strong{display:block;font-size:13px}.pm-room small{color:var(--text-muted)}.pm-players{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.pm-player{border:1px solid var(--border);border-radius:11px;padding:10px;text-align:center;min-height:84px}.pm-player.empty{opacity:.45;border-style:dashed}.pm-av{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;margin:auto auto 6px;color:#fff;font-weight:800}.pm-name{font-size:11px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pm-host{font-size:9px;color:var(--accent)}.pm-code{font:700 20px 'JetBrains Mono',monospace;letter-spacing:.12em;background:var(--bg-input);padding:7px 10px;border-radius:8px}.pm-table{overflow:auto;background:#145532;border:12px solid #71482b;border-radius:15px}.pm-table canvas{display:block;width:100%;height:auto;min-width:760px}.pm-status{text-align:center;color:var(--text-muted);font-size:12px;margin-top:9px}.pm-status b{color:var(--accent)}@media(max-width:760px){.pm-grid{grid-template-columns:1fr}.pm-players{grid-template-columns:repeat(2,1fr)}.pm-shell{height:95vh}}`;document.head.appendChild(s)}
function ui(){css();if($('pool-multi'))return;const b=document.createElement('div');b.id='pool-multi';b.innerHTML='<div class="pm-shell"><div class="pm-head"><span>🎱</span><h2>Yappathon Pool</h2><div class="pm-sp"></div><button class="pm-close" id="pm-close">✕</button></div><div class="pm-body" id="pm-body"></div></div>';document.body.appendChild(b);$('pm-close').onclick=close}
function open(){ui();showLobby();$('pool-multi').classList.add('open')}async function close(){await leave();$('pool-multi')?.classList.remove('open')}
function cleanup(){if(stopRoom){stopRoom();stopRoom=null}if(stopPlayers){stopPlayers();stopPlayers=null}if(stopLobby){stopLobby();stopLobby=null}cancelAnimationFrame(raf);canvas=null;ctx=null;aiming=false;anim=false}
function showLobby(){cleanup();roomId=null;room=null;players.clear();$('pm-body').innerHTML='<div class="pm-grid"><div class="pm-card"><h3>Create a pool room</h3><p>Wait for 2–4 players before the host starts the match.</p><input id="pm-name" class="pm-input" maxlength="28" placeholder="Room name (optional)"><div style="display:flex;justify-content:flex-end;margin-top:10px"><button class="btn primary" id="pm-create">Create room</button></div></div><div class="pm-card"><h3>Join an open room</h3><p>Rooms currently waiting for players.</p><div id="pm-rooms" class="pm-list"><div class="pm-status">Loading…</div></div></div></div>';$('pm-create').onclick=createRoom;listenLobby()}
async function listenLobby(){const{collection,query,where,onSnapshot}=await fs();const q=query(collection(C().db,'poolRooms'),where('status','==','lobby'));stopLobby=onSnapshot(q,s=>{const el=$('pm-rooms');if(!el)return;el.innerHTML='';const docs=s.docs.filter(d=>(d.data().playerCount||0)<4);if(!docs.length){el.innerHTML='<div class="pm-status">No open rooms.</div>';return}docs.forEach(d=>{const x=d.data(),r=document.createElement('div');r.className='pm-room';r.innerHTML=`<div class="meta"><strong>${esc(x.name||'Pool room')}</strong><small>${x.playerCount||0}/4 players</small></div><button class="btn primary">Join</button>`;r.querySelector('button').onclick=()=>joinRoom(d.id);el.appendChild(r)})})}
async function createRoom(){const{addDoc,collection,serverTimestamp}=await fs();const n=($('pm-name').value.trim()||`${uname()}'s room`).slice(0,28);const r=await addDoc(collection(C().db,'poolRooms'),{name:n,status:'lobby',hostUid:uid(),playerCount:0,playerIds:[],state:null,turn:0,createdAt:serverTimestamp()});await joinRoom(r.id)}
async function joinRoom(id){const{doc,runTransaction}=await fs();const ref=doc(C().db,'poolRooms',id);try{await runTransaction(C().db,async tx=>{const s=await tx.get(ref);if(!s.exists())throw Error('Room no longer exists.');const x=s.data(),ids=x.playerIds||[];if(x.status!=='lobby')throw Error('Match already started.');if(!ids.includes(uid())){if(ids.length>=4)throw Error('Room is full.');tx.update(ref,{playerIds:[...ids,uid()],playerCount:ids.length+1})}});roomId=id;await roomView()}catch(e){toast(e.message||'Could not join room.')}}
async function roomView(){const{doc,getDoc,setDoc,collection,onSnapshot,serverTimestamp}=await fs();const ref=doc(C().db,'poolRooms',roomId),s=await getDoc(ref);room=s.data();host=room.hostUid===uid();await setDoc(doc(C().db,'poolRooms',roomId,'players',uid()),{uid:uid(),name:uname(),joinedAt:serverTimestamp()},{merge:true});$('pm-body').innerHTML=`<div class="pm-card"><div style="display:flex;align-items:center;gap:12px"><div><h3>${esc(room.name||'Pool room')}</h3><div class="pm-status" style="text-align:left">Share the code with friends</div></div><div class="pm-sp"></div><div class="pm-code">${roomId.slice(-6).toUpperCase()}</div></div></div><div class="pm-card"><h3>Players</h3><div id="pm-players" class="pm-players"></div><div id="pm-start" style="display:flex;justify-content:center;margin-top:12px"></div></div><div id="pm-game"></div>`;stopPlayers=onSnapshot(collection(C().db,'poolRooms',roomId,'players'),s=>{players.clear();s.forEach(d=>players.set(d.id,d.data()));renderPlayers()});stopRoom=onSnapshot(ref,s=>{if(!s.exists()){showLobby();return}room=s.data();if(room.status==='playing'&&!canvas)startGame(room.state||initial());if(room.status==='playing'&&room.state)applyState(room.state);renderPlayers()})}
function renderPlayers(){const el=$('pm-players');if(!el)return;el.innerHTML='';const arr=[...players.values()];for(let i=0;i<4;i++){const p=arr[i],d=document.createElement('div');d.className='pm-player'+(p?'':' empty');d.innerHTML=p?`<div class="pm-av" style="background:${colors[i]}">${esc((p.name||'?')[0].toUpperCase())}</div><div class="pm-name">${esc(p.name||'Player')}</div>${p.uid===room?.hostUid?'<div class="pm-host">HOST</div>':''}`:'<div class="pm-av" style="background:var(--border)">+</div><div class="pm-name">Waiting…</div>';el.appendChild(d)}const a=$('pm-start');if(!a)return;a.innerHTML='';if(room?.status==='lobby'){if(host){const b=document.createElement('button');b.className='btn primary';b.disabled=players.size<2;b.textContent=players.size<2?'Need 2 players':'Start match';b.onclick=startMatch;a.appendChild(b)}else a.innerHTML='<div class="pm-status">Waiting for host…</div>'}}
function initial(){const bs=[];let n=1;for(let row=0;row<5;row++)for(let col=0;col<=row;col++)bs.push({id:n++,x:690+row*23,y:H/2+(col-row/2)*23,vx:0,vy:0,type:'ball',pocketed:false});bs.push({id:99,x:805,y:H/2,vx:0,vy:0,type:'eight',pocketed:false});bs.unshift({id:0,x:280,y:H/2,vx:0,vy:0,type:'cue',pocketed:false});return{balls:bs,turn:0,shot:0}}
async function startMatch(){if(!host||players.size<2)return;const{doc,updateDoc,serverTimestamp}=await fs();await updateDoc(doc(C().db,'poolRooms',roomId),{status:'playing',state:initial(),turn:0,startedAt:serverTimestamp()})}
function startGame(state){balls=state.balls||initial().balls;turn=state.turn||0;turnUid=[...players.keys()][turn]||uid();const g=$('pm-game');g.innerHTML='<div class="pm-table"><canvas id="pm-canvas" width="1000" height="520"></canvas></div><div class="pm-status" id="pm-status"></div>';canvas=$('pm-canvas');ctx=canvas.getContext('2d');canvas.onpointerdown=e=>{if(turnUid===uid()&&!anim)canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=shoot;last=performance.now();raf=requestAnimationFrame(loop)}
function applyState(s){balls=s.balls||balls;turn=s.turn??turn;turnUid=[...players.keys()][turn]||turnUid}
function moving(){return balls.some(b=>!b.pocketed&&Math.hypot(b.vx,b.vy)>REST)}
async function shoot(e){if(turnUid!==uid()||anim||moving())return;const cue=balls.find(b=>b.type==='cue'&&!b.pocketed);if(!cue)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,dx=cue.x-x,dy=cue.y-y,len=Math.hypot(dx,dy);if(len<10)return;const speed=Math.min(1050,Math.max(120,len*5));cue.vx=dx/len*speed;cue.vy=dy/len*speed;anim=true;await animateShot()}
function physics(dt){const fr=Math.pow(FRICTION,dt*60);for(const b of balls){if(b.pocketed)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=fr;b.vy*=fr;if(Math.hypot(b.vx,b.vy)<REST)b.vx=b.vy=0;if(b.x<R){b.x=R;b.vx=Math.abs(b.vx)*RAIL}if(b.x>W-R){b.x=W-R;b.vx=-Math.abs(b.vx)*RAIL}if(b.y<R){b.y=R;b.vy=Math.abs(b.vy)*RAIL}if(b.y>H-R){b.y=H-R;b.vy=-Math.abs(b.vy)*RAIL}for(const p of pockets)if(Math.hypot(b.x-p[0],b.y-p[1])<POCKET-2){b.pocketed=true;b.vx=b.vy=0}}for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.pocketed||b.pocketed)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d===0){d=.01;dx=.01}if(d<R*2){const nx=dx/d,ny=dy/d,over=R*2-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const imp=-(1+RESTITUTION)*rel/2;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}}}
async function animateShot(){const start=performance.now();return new Promise(resolve=>{let prev=start;const step=t=>{const dt=Math.min(.033,(t-prev)/1000);prev=t;physics(dt);draw();if(moving()&&t-start<12000)requestAnimationFrame(step);else{balls.forEach(b=>{if(Math.hypot(b.vx,b.vy)<REST)b.vx=b.vy=0});anim=false;finishShot().then(resolve)}};requestAnimationFrame(step)})}
async function finishShot(){const ids=[...players.keys()];if(!ids.length)return;turn=(turn+1)%ids.length;turnUid=ids[turn];const{doc,updateDoc}=await fs();await updateDoc(doc(C().db,'poolRooms',roomId),{state:{balls,turn,shot:(room?.state?.shot||0)+1},turn});draw()}
function draw(){if(!ctx)return;ctx.fillStyle='#145532';ctx.fillRect(0,0,W,H);for(const p of pockets){ctx.fillStyle='#080808';ctx.beginPath();ctx.arc(p[0],p[1],POCKET,0,Math.PI*2);ctx.fill()}for(const b of balls){if(b.pocketed)continue;ctx.beginPath();ctx.fillStyle=b.type==='cue'?'#f7f7f7':b.type==='eight'?'#111':colors[(b.id-1)%colors.length];ctx.arc(b.x,b.y,R,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}const st=$('pm-status');if(st)st.innerHTML=`Turn: <b>${esc(players.get(turnUid)?.name||'Player')}</b>${anim?' · balls moving':''}`}
function loop(){if(canvas&&!anim)draw();raf=requestAnimationFrame(loop)}
async function leave(){if(!roomId)return;const id=roomId,wasHost=host;roomId=null;cleanup();try{const{doc,deleteDoc,updateDoc}=await fs();await deleteDoc(doc(C().db,'poolRooms',id,'players',uid()));if(wasHost)await updateDoc(doc(C().db,'poolRooms',id),{status:'finished'})}catch{}room=null;players.clear()}
window.YappathonPool={open,close};ui();setInterval(()=>{const g=$('games-tab');if(!g||g.dataset.poolMulti)return;g.dataset.poolMulti='1';g.innerHTML='<svg class="ui-icon" viewBox="0 0 24 24"><path d="M8 9h8a5 5 0 0 1 4.8 6.4l-.7 2.3a2.5 2.5 0 0 1-4.4.7L14 16H10l-1.7 2.4a2.5 2.5 0 0 1-4.4-.7l-.7-2.3A5 5 0 0 1 8 9Z"/><path d="M8 12v4M6 14h4M16.5 13.5h.01M19 15h.01"/></svg>Multiplayer Games <span class="badge-soon">Pool</span>';g.onclick=open;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}},500);
})();
