(() => {
'use strict';
const FS='https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const C=()=>window.YappathonVoiceContext||{},$=id=>document.getElementById(id),uid=()=>C().currentUser?.uid||'',uname=()=>C().profile?.username||'Player';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let f=null,roomId=null,room=null,players=new Map(),roomUnsub=null,playersUnsub=null,lobbyUnsub=null,host=false;
let canvas=null,ctx=null,balls=[],turn=0,turnUid='',raf=0,last=0,lastWrite=0,shotMoving=false;
const W=1000,H=520,R=11,POCKET=25,RAIL=.84,RESTITUTION=.94,FRICTION=.991,STOP=5;
const pockets=[[0,0],[W/2,0],[W,0],[0,H],[W/2,H],[W,H]],colors=['#FF7A33','#7C8CFF','#4FBE7B','#FF6F9F'];
async function fs(){if(!f)f=await import(FS);return f}function toast(m){C().toast?.(m,'info')}
function css(){if($('pool-final-css'))return;const s=document.createElement('style');s.id='pool-final-css';s.textContent=`#pool-final{position:fixed;inset:0;z-index:1600;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(0,0,0,.72);backdrop-filter:blur(10px)}#pool-final.open{display:flex}.pf2{width:min(1120px,100%);height:min(92vh,820px);background:var(--bg-elevated);border:1px solid var(--border);border-radius:20px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 100px var(--shadow)}.pf2head{display:flex;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid var(--border)}.pf2head h2{margin:0;font-size:18px}.pf2sp{flex:1}.pf2close{background:none;border:0;color:var(--text-muted);font-size:20px}.pf2body{flex:1;min-height:0;overflow:auto;padding:16px}.pf2grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pf2card{background:var(--bg-alt);border:1px solid var(--border);border-radius:14px;padding:16px}.pf2card h3{font-size:15px;margin:0 0 8px}.pf2card p{font-size:12px;line-height:1.5;color:var(--text-muted);margin:0 0 12px}.pf2input{width:100%;background:var(--bg-input);border:1px solid var(--border);color:var(--text);border-radius:9px;padding:10px;font:inherit}.pf2list{display:grid;gap:7px;max-height:300px;overflow:auto}.pf2room{display:flex;align-items:center;gap:10px;background:var(--bg-input);border:1px solid var(--border);border-radius:10px;padding:10px}.pf2room .meta{flex:1;min-width:0}.pf2room strong{display:block;font-size:13px}.pf2room small{color:var(--text-muted)}.pf2players{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.pf2player{text-align:center;padding:10px;border:1px solid var(--border);border-radius:11px;min-height:84px}.pf2player.empty{opacity:.45;border-style:dashed}.pf2av{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;margin:auto auto 6px;color:#fff;font-weight:800}.pf2name{font-size:11px;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pf2host{font-size:9px;color:var(--accent)}.pf2code{font:700 20px 'JetBrains Mono',monospace;letter-spacing:.12em;background:var(--bg-input);padding:7px 10px;border-radius:8px}.pf2table{overflow:auto;background:#145532;border:12px solid #71482b;border-radius:15px}.pf2table canvas{display:block;width:100%;height:auto;min-width:760px}.pf2status{text-align:center;color:var(--text-muted);font-size:12px;margin-top:9px}.pf2status b{color:var(--accent)}@media(max-width:760px){.pf2grid{grid-template-columns:1fr}.pf2players{grid-template-columns:repeat(2,1fr)}.pf2{height:95vh}}`;document.head.appendChild(s)}
function ui(){css();if($('pool-final'))return;const b=document.createElement('div');b.id='pool-final';b.innerHTML='<div class="pf2"><div class="pf2head"><span>🎱</span><h2>Yappathon Pool</h2><div class="pf2sp"></div><button class="pf2close" id="pf2close">✕</button></div><div class="pf2body" id="pf2body"></div></div>';document.body.appendChild(b);$('pf2close').onclick=close}
function open(){ui();lobby();$('pool-final').classList.add('open')}async function close(){await leave();$('pool-final')?.classList.remove('open')}
function stop(){if(roomUnsub){roomUnsub();roomUnsub=null}if(playersUnsub){playersUnsub();playersUnsub=null}if(lobbyUnsub){lobbyUnsub();lobbyUnsub=null}cancelAnimationFrame(raf);canvas=null;ctx=null}
function lobby(){stop();roomId=null;room=null;players.clear();$('pf2body').innerHTML='<div class="pf2grid"><div class="pf2card"><h3>Create a pool room</h3><p>Wait for 2–4 players before the host starts the match.</p><input id="pf2name" class="pf2input" maxlength="28" placeholder="Room name (optional)"><div style="display:flex;justify-content:flex-end;margin-top:10px"><button class="btn primary" id="pf2create">Create room</button></div></div><div class="pf2card"><h3>Join an open room</h3><p>Rooms currently waiting for players.</p><div id="pf2rooms" class="pf2list"><div class="pf2status">Loading…</div></div></div></div>';$('pf2create').onclick=createRoom;listenRooms()}
async function listenRooms(){const {collection,query,where,onSnapshot}=await fs();const q=query(collection(C().db,'poolRooms'),where('status','==','lobby'));lobbyUnsub=onSnapshot(q,s=>{const el=$('pf2rooms');if(!el)return;el.innerHTML='';const docs=s.docs.filter(d=>(d.data().playerCount||0)<4);if(!docs.length){el.innerHTML='<div class="pf2status">No open rooms.</div>';return}docs.forEach(d=>{const x=d.data(),r=document.createElement('div');r.className='pf2room';r.innerHTML=`<div class="meta"><strong>${esc(x.name||'Pool room')}</strong><small>${x.playerCount||0}/4 players</small></div><button class="btn primary">Join</button>`;r.querySelector('button').onclick=()=>joinRoom(d.id);el.appendChild(r)})})}
async function createRoom(){const {addDoc,collection,serverTimestamp}=await fs();const n=($('pf2name').value.trim()||`${uname()}'s room`).slice(0,28);const r=await addDoc(collection(C().db,'poolRooms'),{name:n,status:'lobby',hostUid:uid(),playerCount:0,playerIds:[],state:null,turn:0,createdAt:serverTimestamp()});await joinRoom(r.id)}
async function joinRoom(id){const {doc,runTransaction}=await fs();const ref=doc(C().db,'poolRooms',id);try{await runTransaction(C().db,async tx=>{const s=await tx.get(ref);if(!s.exists())throw Error('Room no longer exists.');const x=s.data(),ids=x.playerIds||[];if(x.status!=='lobby')throw Error('Match already started.');if(!ids.includes(uid())){if(ids.length>=4)throw Error('Room is full.');tx.update(ref,{playerIds:[...ids,uid()],playerCount:ids.length+1})}});roomId=id;await roomView()}catch(e){toast(e.message||'Could not join room.')}}
async function roomView(){const {doc,getDoc,setDoc,collection,onSnapshot,serverTimestamp}=await fs();const ref=doc(C().db,'poolRooms',roomId),s=await getDoc(ref);room=s.data();host=room.hostUid===uid();await setDoc(doc(C().db,'poolRooms',roomId,'players',uid()),{uid:uid(),name:uname(),joinedAt:serverTimestamp()},{merge:true});$('pf2body').innerHTML=`<div class="pf2card"><div style="display:flex;align-items:center;gap:12px"><div><h3>${esc(room.name||'Pool room')}</h3><div class="pf2status" style="text-align:left">Share the code with friends</div></div><div class="pf2sp"></div><div class="pf2code">${roomId.slice(-6).toUpperCase()}</div></div></div><div class="pf2card"><h3>Players</h3><div id="pf2players" class="pf2players"></div><div id="pf2start" style="display:flex;justify-content:center;margin-top:12px"></div></div><div id="pf2game"></div>`;playersUnsub=onSnapshot(collection(C().db,'poolRooms',roomId,'players'),s=>{players.clear();s.forEach(d=>players.set(d.id,d.data()));renderPlayers()});roomUnsub=onSnapshot(ref,s=>{if(!s.exists()){lobby();return}room=s.data();if(room.status==='playing'){if(!canvas)startGame(room.state||initial());if(!host&&room.state)apply(room.state)}renderPlayers()})}
function renderPlayers(){const el=$('pf2players');if(!el)return;el.innerHTML='';const arr=[...players.values()];for(let i=0;i<4;i++){const p=arr[i],d=document.createElement('div');d.className='pf2player'+(p?'':' empty');d.innerHTML=p?`<div class="pf2av" style="background:${colors[i]}">${esc((p.name||'?')[0].toUpperCase())}</div><div class="pf2name">${esc(p.name||'Player')}</div>${p.uid===room?.hostUid?'<div class="pf2host">HOST</div>':''}`:'<div class="pf2av" style="background:var(--border)">+</div><div class="pf2name">Waiting…</div>';el.appendChild(d)}const a=$('pf2start');if(!a)return;a.innerHTML='';if(room?.status==='lobby'){if(host){const b=document.createElement('button');b.className='btn primary';b.disabled=players.size<2;b.textContent=players.size<2?'Need 2 players':'Start match';b.onclick=startMatch;a.appendChild(b)}else a.innerHTML='<div class="pf2status">Waiting for host…</div>'}}
function initial(){const bs=[];let n=1;for(let row=0;row<5;row++)for(let col=0;col<=row;col++)bs.push({id:n++,x:690+row*23,y:H/2+(col-row/2)*23,vx:0,vy:0,type:'ball',pocketed:false});bs.push({id:99,x:805,y:H/2,vx:0,vy:0,type:'eight',pocketed:false});bs.unshift({id:0,x:280,y:H/2,vx:0,vy:0,type:'cue',pocketed:false});return{balls:bs,turn:0,active:false,shot:0}}
async function startMatch(){if(!host||players.size<2)return;const {doc,updateDoc,serverTimestamp}=await fs();await updateDoc(doc(C().db,'poolRooms',roomId),{status:'playing',state:initial(),turn:0,startedAt:serverTimestamp()})}
function startGame(state){balls=state.balls||initial().balls;turn=state.turn||0;turnUid=[...players.keys()][turn]||uid();const g=$('pf2game');g.innerHTML='<div class="pf2table"><canvas id="pf2canvas" width="1000" height="520"></canvas></div><div class="pf2status" id="pf2status"></div>';canvas=$('pf2canvas');ctx=canvas.getContext('2d');canvas.onpointerdown=e=>{if(host&&turnUid===uid()&&!moving())canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=shoot;last=performance.now();lastWrite=0;raf=requestAnimationFrame(loop)}
function apply(s){balls=s.balls||balls;turn=s.turn??turn;turnUid=[...players.keys()][turn]||turnUid}
function moving(){return balls.some(b=>!b.pocketed&&Math.hypot(b.vx,b.vy)>STOP)}
async function shoot(e){if(!host||turnUid!==uid()||moving())return;const cue=balls.find(b=>b.type==='cue'&&!b.pocketed);if(!cue)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,dx=cue.x-x,dy=cue.y-y,len=Math.hypot(dx,dy);if(len<10)return;const v=Math.min(1050,Math.max(120,len*5));cue.vx=dx/len*v;cue.vy=dy/len*v;shotMoving=true;await write(true)}
function physics(dt){const fr=Math.pow(FRICTION,dt*60);for(const b of balls){if(b.pocketed)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=fr;b.vy*=fr;if(Math.hypot(b.vx,b.vy)<STOP)b.vx=b.vy=0;if(b.x<R){b.x=R;b.vx=Math.abs(b.vx)*RAIL}if(b.x>W-R){b.x=W-R;b.vx=-Math.abs(b.vx)*RAIL}if(b.y<R){b.y=R;b.vy=Math.abs(b.vy)*RAIL}if(b.y>H-R){b.y=H-R;b.vy=-Math.abs(b.vy)*RAIL}for(const p of pockets)if(Math.hypot(b.x-p[0],b.y-p[1])<POCKET-2){b.pocketed=true;b.vx=b.vy=0}}
for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.pocketed||b.pocketed)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d===0){d=.01;dx=.01}if(d<R*2){const nx=dx/d,ny=dy/d,over=R*2-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const imp=-(1+RESTITUTION)*rel/2;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}}}
function draw(){if(!ctx)return;ctx.fillStyle='#145532';ctx.fillRect(0,0,W,H);for(const p of pockets){ctx.fillStyle='#080808';ctx.beginPath();ctx.arc(p[0],p[1],POCKET,0,Math.PI*2);ctx.fill()}for(const b of balls){if(b.pocketed)continue;ctx.beginPath();ctx.fillStyle=b.type==='cue'?'#f7f7f7':b.type==='eight'?'#111':colors[(b.id-1)%colors.length];ctx.arc(b.x,b.y,R,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()}const st=$('pf2status');if(st)st.innerHTML=`Turn: <b>${esc(players.get(turnUid)?.name||'Player')}</b>${moving()?' · balls moving':''}`}
async function write(active){if(!host)return;const {doc,updateDoc}=await fs();await updateDoc(doc(C().db,'poolRooms',roomId),{state:{balls,turn,active,shot:(room?.state?.shot||0)+1},turn})}
async function next(){if(!host||moving())return;const ids=[...players.keys()];if(!ids.length)return;turn=(turn+1)%ids.length;turnUid=ids[turn];shotMoving=false;await write(false)}
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;if(canvas){if(host){physics(dt);if(moving()&&t-lastWrite>120){lastWrite=t;write(true).catch(()=>{})}if(!moving()&&shotMoving)next().catch(()=>{})}draw()}raf=requestAnimationFrame(loop)}
async function leave(){if(!roomId)return;const id=roomId,wasHost=host;roomId=null;stop();try{const {doc,deleteDoc,updateDoc}=await fs();await deleteDoc(doc(C().db,'poolRooms',id,'players',uid()));if(wasHost)await updateDoc(doc(C().db,'poolRooms',id),{status:'finished'})}catch{}room=null;players.clear()}
window.YappathonPool={open,close};ui();
setInterval(()=>{const g=$('games-tab');if(!g||g.dataset.poolFinal)return;g.dataset.poolFinal='1';g.innerHTML='<svg class="ui-icon" viewBox="0 0 24 24"><path d="M8 9h8a5 5 0 0 1 4.8 6.4l-.7 2.3a2.5 2.5 0 0 1-4.4.7L14 16H10l-1.7 2.4a2.5 2.5 0 0 1-4.4-.7l-.7-2.3A5 5 0 0 1 8 9Z"/><path d="M8 12v4M6 14h4M16.5 13.5h.01M19 15h.01"/></svg>Multiplayer Games <span class="badge-soon">Pool</span>';g.onclick=open;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}},500);
})();
