(() => {
  'use strict';
  const F='https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
  const C=()=>window.YappathonVoiceContext||{};
  const $=id=>document.getElementById(id);
  const uid=()=>C().currentUser?.uid||'';
  const username=()=>C().profile?.username||'Player';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let fs,roomId=null,room=null,players=new Map(),roomStop=null,playersStop=null,lobbyStop=null;
  let canvas,ctx,raf=0,last=0,host=false,balls=[],turnUid='',movingShot=false,lastWrite=0;
  const W=1000,H=520,R=11,POCKET=25,RAIL=.84,BALL=.94,FRICTION=.991,STOP=5;
  const pockets=[[0,0],[W/2,0],[W,0],[0,H],[W/2,H],[W,H]];
  const colors=['#FF7A33','#7C8CFF','#4FBE7B','#FF6F9F'];
  async function firestore(){if(!fs)fs=await import(F);return fs}
  function toast(x){if(typeof C().toast==='function')C().toast(x,'info');else console.log(x)}
  function addStyle(){if($('pool-fixed-style'))return;const s=document.createElement('style');s.id='pool-fixed-style';s.textContent=`#pool-fixed{position:fixed;inset:0;z-index:1600;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(0,0,0,.72);backdrop-filter:blur(10px)}#pool-fixed.open{display:flex}.pf-shell{width:min(1120px,100%);height:min(92vh,820px);background:var(--bg-elevated);border:1px solid var(--border);border-radius:20px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 100px var(--shadow)}.pf-head{display:flex;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid var(--border)}.pf-head h2{font-size:18px;margin:0}.pf-spacer{flex:1}.pf-close{border:0;background:none;color:var(--text-muted);font-size:20px;padding:5px 8px;border-radius:8px}.pf-close:hover{background:var(--bg-input);color:var(--text)}.pf-body{overflow:auto;min-height:0;flex:1;padding:16px}.pf-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pf-card{background:var(--bg-alt);border:1px solid var(--border);border-radius:14px;padding:16px}.pf-card h3{margin:0 0 8px;font-size:15px}.pf-card p{margin:0 0 12px;color:var(--text-muted);font-size:12px;line-height:1.5}.pf-input{width:100%;padding:10px 12px;background:var(--bg-input);border:1px solid var(--border);border-radius:9px;color:var(--text);font:inherit}.pf-list{display:grid;gap:7px;max-height:300px;overflow:auto}.pf-room{display:flex;align-items:center;gap:10px;padding:10px;border:1px solid var(--border);border-radius:10px;background:var(--bg-input)}.pf-room .meta{min-width:0;flex:1}.pf-room strong{display:block;font-size:13px}.pf-room small{color:var(--text-muted)}.pf-players{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.pf-player{padding:10px;border:1px solid var(--border);border-radius:11px;text-align:center;min-height:85px}.pf-player.empty{opacity:.45;border-style:dashed}.pf-avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;margin:auto auto 6px;color:#fff;font-weight:800}.pf-name{font-size:11px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pf-host{font-size:9px;color:var(--accent);margin-top:2px}.pf-code{font:700 22px 'JetBrains Mono',monospace;letter-spacing:.14em;background:var(--bg-input);padding:7px 10px;border-radius:9px}.pf-table{overflow:auto;background:#12502f;border:12px solid #71482b;border-radius:15px}.pf-table canvas{display:block;width:100%;height:auto;min-width:760px}.pf-status{text-align:center;color:var(--text-muted);font-size:12px;margin-top:9px}.pf-status b{color:var(--accent)}.pf-actions{display:flex;justify-content:center;gap:8px;margin-top:12px}@media(max-width:760px){.pf-grid{grid-template-columns:1fr}.pf-players{grid-template-columns:repeat(2,1fr)}.pf-shell{height:95vh}}`;document.head.appendChild(s)}
  function ui(){addStyle();if($('pool-fixed'))return;const b=document.createElement('div');b.id='pool-fixed';b.innerHTML='<div class="pf-shell"><div class="pf-head"><span>🎱</span><h2>Yappathon Pool</h2><div class="pf-spacer"></div><button class="pf-close" id="pf-close">✕</button></div><div class="pf-body" id="pf-body"></div></div>';document.body.appendChild(b);$('pf-close').onclick=close}
  function open(){ui();showLobby();$('pool-fixed').classList.add('open')}
  async function close(){await leave();$('pool-fixed')?.classList.remove('open')}
  function stop(){if(roomStop){roomStop();roomStop=null}if(playersStop){playersStop();playersStop=null}if(lobbyStop){lobbyStop();lobbyStop=null}cancelAnimationFrame(raf)}
  function showLobby(){stop();roomId=null;room=null;players.clear();const b=$('pf-body');b.innerHTML='<div class="pf-grid"><div class="pf-card"><h3>Create a pool room</h3><p>Wait for 2–4 players, then the host starts the match.</p><input class="pf-input" id="pf-room-name" maxlength="28" placeholder="Room name (optional)"><div class="pf-actions"><button class="btn primary" id="pf-create">Create room</button></div></div><div class="pf-card"><h3>Join an open room</h3><p>Rooms currently waiting for players.</p><div class="pf-list" id="pf-list"><div class="pf-status">Loading…</div></div></div></div>';$('pf-create').onclick=createRoom;listenLobby()}
  async function listenLobby(){const {collection,query,where,onSnapshot}=await firestore();const q=query(collection(C().db,'poolRooms'),where('status','==','lobby'));lobbyStop=onSnapshot(q,s=>{const el=$('pf-list');if(!el)return;el.innerHTML='';const rooms=s.docs.filter(d=>(d.data().playerCount||0)<4);if(!rooms.length){el.innerHTML='<div class="pf-status">No open rooms.</div>';return}rooms.forEach(d=>{const x=d.data(),r=document.createElement('div');r.className='pf-room';r.innerHTML=`<div class="meta"><strong>${esc(x.name||'Pool room')}</strong><small>${x.playerCount||0}/4 players</small></div><button class="btn primary">Join</button>`;r.querySelector('button').onclick=()=>join(d.id);el.appendChild(r)})})}
  async function createRoom(){const {addDoc,collection,serverTimestamp}=await firestore();const n=($('pf-room-name').value.trim()||`${username()}'s room`).slice(0,28);const ref=await addDoc(collection(C().db,'poolRooms'),{name:n,status:'lobby',hostUid:uid(),playerCount:0,playerIds:[],state:null,turn:0,createdAt:serverTimestamp()});await join(ref.id)}
  async function join(id){const {doc,runTransaction}=await firestore();const ref=doc(C().db,'poolRooms',id);try{await runTransaction(C().db,async tx=>{const s=await tx.get(ref);if(!s.exists())throw Error('Room no longer exists.');const x=s.data(),ids=x.playerIds||[];if(x.status!=='lobby')throw Error('Match already started.');if(ids.includes(uid()))return;if(ids.length>=4)throw Error('Room is full.');tx.update(ref,{playerIds:[...ids,uid()],playerCount:ids.length+1})});roomId=id;await roomView()}catch(e){toast(e.message||'Could not join room.')}}
  async function roomView(){const {doc,getDoc,setDoc,collection,onSnapshot,serverTimestamp}=await firestore();const ref=doc(C().db,'poolRooms',roomId),s=await getDoc(ref);room=s.data();host=room.hostUid===uid();await setDoc(doc(C().db,'poolRooms',roomId,'players',uid()),{uid:uid(),name:username(),joinedAt:serverTimestamp()},{merge:true});$('pf-body').innerHTML=`<div class="pf-card"><div style="display:flex;align-items:center;gap:12px"><div><h3>${esc(room.name||'Pool room')}</h3><div class="pf-status" style="text-align:left">Share this code with friends</div></div><div class="pf-spacer"></div><div class="pf-code">${roomId.slice(-6).toUpperCase()}</div></div></div><div class="pf-card"><h3>Players</h3><div class="pf-players" id="pf-players"></div><div class="pf-actions" id="pf-start"></div></div><div id="pf-game"></div>`;playersStop=onSnapshot(collection(C().db,'poolRooms',roomId,'players'),s=>{players.clear();s.forEach(d=>players.set(d.id,d.data()));renderPlayers()});roomStop=onSnapshot(ref,s=>{if(!s.exists()){showLobby();return}room=s.data();if(room.status==='playing'){if(!canvas)startGame(room.state||initial());if(!host&&room.state)applyState(room.state)}renderPlayers()})}
  function renderPlayers(){const el=$('pf-players');if(!el)return;el.innerHTML='';const list=[...players.values()];for(let i=0;i<4;i++){const p=list[i],d=document.createElement('div');d.className='pf-player'+(p?'':' empty');d.innerHTML=p?`<div class="pf-avatar" style="background:${colors[i]}">${esc((p.name||'?')[0].toUpperCase())}</div><div class="pf-name">${esc(p.name||'Player')}</div>${p.uid===room?.hostUid?'<div class="pf-host">HOST</div>':''}`:'<div class="pf-avatar" style="background:var(--border)">+</div><div class="pf-name">Waiting…</div>';el.appendChild(d)}const a=$('pf-start');if(!a)return;a.innerHTML='';if(room?.status==='lobby'){if(host){const b=document.createElement('button');b.className='btn primary';b.disabled=players.size<2;b.textContent=players.size<2?'Need 2 players':'Start match';b.onclick=start;a.appendChild(b)}else a.innerHTML='<div class="pf-status">Waiting for host…</div>'}}
  function initial(){const bs=[];let id=1;for(let row=0;row<5;row++)for(let col=0;col<=row;col++)bs.push({id:id++,x:690+row*23,y:H/2+(col-row/2)*23,vx:0,vy:0,type:'ball',pocketed:false});bs.push({id:99,x:690+5*23,y:H/2,vx:0,vy:0,type:'eight',pocketed:false});bs.unshift({id:0,x:280,y:H/2,vx:0,vy:0,type:'cue',pocketed:false});return{balls:bs,turn:0,active:false,shot:0}}
  async function start(){if(!host||players.size<2)return;const {doc,updateDoc,serverTimestamp}=await firestore();await updateDoc(doc(C().db,'poolRooms',roomId),{status:'playing',state:initial(),turn:0,startedAt:serverTimestamp()})}
  function startGame(state){balls=state.balls||initial().balls;turn=state.turn||0;turnUid=[...players.keys()][turn]||uid();canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;canvas.style.cssText='width:100%;height:auto;min-width:760px;display:block';ctx=canvas.getContext('2d');const wrap=$('pf-game');wrap.innerHTML='<div class="pf-table" id="pf-table"></div><div class="pf-status" id="pf-status"></div>';$('pf-table').appendChild(canvas);canvas.onpointerdown=shootStart;canvas.onpointerup=shootEnd;last=performance.now();raf=requestAnimationFrame(loop)}
  function applyState(s){balls=s.balls||balls;turn=s.turn??turn;turnUid=[...players.keys()][turn]||turnUid}
  function startGame(s){canvas=null;startGame(s)}
  function shootStart(e){if(!host||turnUid!==uid()||moving())return;canvas.setPointerCapture(e.pointerId)}
  async function shootEnd(e){if(!host||turnUid!==uid()||moving())return;const cue=balls.find(b=>b.type==='cue'&&!b.pocketed);if(!cue)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height,dx=cue.x-x,dy=cue.y-y,len=Math.hypot(dx,dy);if(len<10)return;const speed=Math.min(1050,Math.max(120,len*5));cue.vx=dx/len*speed;cue.vy=dy/len*speed;movingShot=true;await write(true)}
  function moving(){return balls.some(b=>!b.pocketed&&Math.hypot(b.vx,b.vy)>STOP)}
  function physics(dt){const fr=Math.pow(FRICTION,dt*60);for(const b of balls){if(b.pocketed)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.vx*=fr;b.vy*=fr;if(Math.hypot(b.vx,b.vy)<STOP)b.vx=b.vy=0;if(b.x<R){b.x=R;b.vx=Math.abs(b.vx)*RAIL}if(b.x>W-R){b.x=W-R;b.vx=-Math.abs(b.vx)*RAIL}if(b.y<R){b.y=R;b.vy=Math.abs(b.vy)*RAIL}if(b.y>H-R){b.y=H-R;b.vy=-Math.abs(b.vy)*RAIL}for(const [px,py] of pockets)if(Math.hypot(b.x-px,b.y-py)<POCKET-2){b.pocketed=true;b.vx=b.vy=0}}
    for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.pocketed||b.pocketed)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d===0){dx=.01;d=.01}if(d<R*2){const nx=dx/d,ny=dy/d,over=R*2-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const imp=-(1+BALL)*rel/2;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}}}
  function draw(){if(!ctx)return;ctx.fillStyle='#145234';ctx.fillRect(0,0,W,H);for(const p of pockets){ctx.fillStyle='#080808';ctx.beginPath();ctx.arc(p[0],p[1],POCKET,0,Math.PI*2);ctx.fill()}balls.forEach(b=>{if(b.pocketed)return;ctx.beginPath();ctx.fillStyle=b.type==='cue'?'#f7f7f7':b.type==='eight'?'#111':colors[(b.id-1)%colors.length];ctx.arc(b.x,b.y,R,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke()});const st=$('pf-status');if(st)st.innerHTML=`Turn: <b>${esc(players.get(turnUid)?.name||'Player')}</b>${moving()?' · balls moving':''}`}
  async function write(active){if(!host)return;const {doc,updateDoc}=await firestore();await updateDoc(doc(C().db,'poolRooms',roomId),{state:{balls,turn,active,shot:(room?.state?.shot||0)+1},turn})}
  async function nextTurn(){if(!host||moving())return;const ids=[...players.keys()];if(!ids.length)return;turn=(turn+1)%ids.length;turnUid=ids[turn];movingShot=false;await write(false)}
  function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;if(canvas){if(host){physics(dt);if(moving()&&t-lastWrite>120){lastWrite=t;write(true).catch(()=>{})}if(!moving()&&movingShot){nextTurn().catch(()=>{})}}draw()}raf=requestAnimationFrame(loop)}
  async function leave(){if(!roomId)return;const id=roomId;roomId=null;const wasHost=host;stop();try{const {doc,deleteDoc,updateDoc}=await firestore();await deleteDoc(doc(C().db,'poolRooms',id,'players',uid()));if(wasHost)await updateDoc(doc(C().db,'poolRooms',id),{status:'finished'})}catch{}canvas=null;room=null;players.clear()}
  let lastWrite=0;
  window.YappathonPool={open,close};
  ui();
  setInterval(()=>{const g=$('games-tab');if(!g||g.dataset.poolFixed)return;g.dataset.poolFixed='1';g.innerHTML='<svg class="ui-icon" viewBox="0 0 24 24"><path d="M8 9h8a5 5 0 0 1 4.8 6.4l-.7 2.3a2.5 2.5 0 0 1-4.4.7L14 16H10l-1.7 2.4a2.5 2.5 0 0 1-4.4-.7l-.7-2.3A5 5 0 0 1 8 9Z"/><path d="M8 12v4M6 14h4M16.5 13.5h.01M19 15h.01"/></svg>Multiplayer Games <span class="badge-soon">Pool</span>';g.onclick=open;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}},500);
})();
