import {
  doc,getDoc,setDoc,updateDoc,deleteDoc,addDoc,collection,onSnapshot,query,where,serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const C=()=>window.YappathonVoiceContext||{};
const db=()=>C().db, me=()=>C().currentUser, profile=()=>C().profile||{}, cache=()=>C().userCache||{};
const RTC={iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"}]};
const CALL_FRESH_MS=45000, INVITE_FRESH_MS=30000;
let localStream=null,activeCall=null,incoming=null,muted=false;
let stopInvites=null,stopSignals=null,stopPresence=null,heartbeat=null;
const peers=new Map(),queuedIce=new Map();
const id=()=>me()?.uid||"";
const callRef=x=>doc(db(),"voiceCalls",x), invRef=(x,u)=>doc(db(),"voiceCalls",x,"invites",u), presRef=(x,u)=>doc(db(),"voiceCalls",x,"presence",u), sigCol=x=>collection(db(),"voiceCalls",x,"signals");
const toast=m=>typeof C().toast==="function"?C().toast(m,"info"):console.log(m);
const fresh=t=>t?.toMillis&&Date.now()-t.toMillis()<CALL_FRESH_MS;
const inviteFresh=t=>t?.toMillis&&Date.now()-t.toMillis()<INVITE_FRESH_MS;
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));

function style(){if(document.getElementById("yappathon-voice-style"))return;const s=document.createElement("style");s.id="yappathon-voice-style";s.textContent=`
.voice-start-btn{margin-left:auto;display:inline-flex;align-items:center;gap:6px;border:1px solid var(--border);background:var(--bg-input);color:var(--text);border-radius:8px;padding:6px 10px;font-size:12px;font-weight:700}.voice-start-btn:hover{background:var(--accent-soft);border-color:var(--accent);color:var(--accent)}
.voice-overlay{position:fixed;inset:0;z-index:10050;background:rgba(0,0,0,.58);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:20px}.voice-card{width:min(420px,100%);background:var(--bg-alt);border:1px solid var(--border);border-radius:18px;padding:26px;box-shadow:0 24px 80px var(--shadow)}.voice-kicker{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:var(--accent);font-weight:800}.voice-card h2{margin:7px 0;font-size:23px}.voice-card p{margin:0;color:var(--text-muted)}.voice-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:22px}.voice-btn{border:1px solid var(--border);border-radius:9px;padding:9px 15px;background:var(--bg-input);color:var(--text);font-weight:700}.voice-btn.primary{background:var(--accent);color:var(--accent-contrast);border-color:var(--accent)}.voice-btn.danger{color:#fff;background:var(--danger);border-color:var(--danger)}
.voice-panel{position:fixed;right:20px;bottom:20px;z-index:10040;width:min(360px,calc(100vw - 40px));background:var(--bg-alt);border:1px solid var(--border);border-radius:16px;box-shadow:0 20px 70px var(--shadow);overflow:hidden}.voice-head{display:flex;justify-content:space-between;align-items:center;padding:13px 14px;border-bottom:1px solid var(--border)}.voice-head span{font-size:11px;color:var(--text-muted)}.voice-people{padding:10px;max-height:240px;overflow:auto}.voice-person{display:flex;justify-content:space-between;padding:9px 10px;border-radius:9px;background:var(--bg-elevated);margin-bottom:5px}.voice-person span{font-size:11px;color:var(--online)}.voice-controls{display:flex;gap:7px;padding:10px;border-top:1px solid var(--border)}.voice-control{flex:1;border:1px solid var(--border);background:var(--bg-input);color:var(--text);border-radius:8px;padding:8px;font-weight:700}.voice-control.danger{color:#fff;background:var(--danger);border-color:var(--danger)}@media(max-width:600px){.voice-panel{right:10px;bottom:10px;width:calc(100vw - 20px)}}`;
document.head.appendChild(s)}
function ui(){if(document.getElementById("voice-root"))return;const r=document.createElement("div");r.id="voice-root";r.innerHTML=`<div class="voice-overlay" id="voice-incoming" hidden><div class="voice-card"><div class="voice-kicker">Incoming voice call</div><h2 id="voice-title-in">Incoming call</h2><p id="voice-sub-in">Someone is calling you.</p><div class="voice-actions"><button class="voice-btn danger" id="voice-decline">Decline</button><button class="voice-btn primary" id="voice-accept">Accept</button></div></div></div><div class="voice-panel" id="voice-panel" hidden><div class="voice-head"><div><strong id="voice-name">Voice</strong><br><span id="voice-count">1 person</span></div><button class="voice-control" id="voice-leave-x">×</button></div><div class="voice-people" id="voice-people"></div><div class="voice-controls"><button class="voice-control" id="voice-mute">🎙️ Mute</button><button class="voice-control danger" id="voice-leave">☎ Leave</button></div></div>`;document.body.appendChild(r);$("voice-accept").onclick=accept;$("voice-decline").onclick=decline;$("voice-leave").onclick=leave;$("voice-leave-x").onclick=leave;$("voice-mute").onclick=toggleMute}
function $(x){return document.getElementById(x)}
function ctx(){const c=C();if(c.currentConvoType==="channel"&&c.currentChannel)return{type:"channel",id:c.currentChannel,name:"#"+c.currentChannel,members:[]};if(c.currentConvoType==="dm"&&c.currentDmId){const d=c.dmCache?.[c.currentDmId];if(!d)return null;return{type:d.type==="group"?"group":"dm",id:c.currentDmId,name:d.name||null,members:Array.isArray(d.members)?d.members:[]}}return null}
function callId(c){return(c.type==="channel"?"channel_":"call_")+c.id}
function title(c){return c.type==="channel"?c.name+" voice":c.type==="group"?(c.name||"Group voice"):"Voice call"}
async function mic(){if(localStream)return;localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}
function stopMic(){if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}}
function audio(u,stream){let a=document.querySelector(`audio[data-yv="${CSS.escape(u)}"]`);if(!a){a=document.createElement("audio");a.autoplay=true;a.dataset.yv=u;a.style.display="none";document.body.appendChild(a)}a.srcObject=stream}
function peer(u){if(peers.has(u))return peers.get(u);const p=new RTCPeerConnection(RTC);localStream?.getTracks().forEach(t=>p.addTrack(t,localStream));p.onicecandidate=e=>{if(e.candidate&&activeCall)addDoc(sigCol(activeCall.id),{type:"candidate",from:id(),to:u,candidate:e.candidate.toJSON(),createdAt:serverTimestamp()}).catch(()=>{})};p.ontrack=e=>audio(u,e.streams[0]);p.onconnectionstatechange=()=>{if(["failed","closed"].includes(p.connectionState)){p.close();peers.delete(u);render()}};peers.set(u,p);return p}
async function offer(u){if(!activeCall||id()>=u)return;const p=peer(u);if(p.signalingState!=="stable")return;const o=await p.createOffer();await p.setLocalDescription(o);await addDoc(sigCol(activeCall.id),{type:"offer",from:id(),to:u,offer:{type:o.type,sdp:o.sdp},createdAt:serverTimestamp()})}
function signals(call){if(stopSignals)stopSignals();stopSignals=onSnapshot(sigCol(call),async snap=>{for(const ch of snap.docChanges()){if(ch.type!=="added")continue;const s=ch.doc.data();if(s.to!==id()||!activeCall)continue;try{if(s.type==="offer"){const p=peer(s.from);if(p.signalingState!=="stable")continue;await p.setRemoteDescription(s.offer);for(const c of queuedIce.get(s.from)||[])await p.addIceCandidate(c);queuedIce.delete(s.from);const a=await p.createAnswer();await p.setLocalDescription(a);await addDoc(sigCol(call),{type:"answer",from:id(),to:s.from,answer:{type:a.type,sdp:a.sdp},createdAt:serverTimestamp()})}else if(s.type==="answer"){const p=peers.get(s.from);if(p){await p.setRemoteDescription(s.answer);for(const c of queuedIce.get(s.from)||[])await p.addIceCandidate(c);queuedIce.delete(s.from)}}else if(s.type==="candidate"){const p=peers.get(s.from);if(p?.remoteDescription)await p.addIceCandidate(s.candidate);else{const q=queuedIce.get(s.from)||[];q.push(s.candidate);queuedIce.set(s.from,q)}}}catch(e){console.warn("Voice signaling error",e)}}})}
function presence(call,on){const p=presRef(call,id());return on?setDoc(p,{uid:id(),name:profile().username||"Member",photoBase64:profile().photoBase64||null,joinedAt:serverTimestamp()}):deleteDoc(p).catch(()=>{})}
function presenceWatch(call){if(stopPresence)stopPresence();stopPresence=onSnapshot(collection(db(),"voiceCalls",call,"presence"),async snap=>{for(const ch of snap.docChanges())if(ch.type==="added"&&ch.doc.id!==id()&&activeCall&&!peers.has(ch.doc.id))try{await offer(ch.doc.id)}catch(e){console.warn(e)}render()})}
function render(){if(!activeCall)return;$("voice-name").textContent=title(activeCall.context);const p=$("voice-people");p.innerHTML="";const self=document.createElement("div");self.className="voice-person";self.innerHTML=`<strong>${esc(profile().username||"You")}</strong><span>You</span>`;p.appendChild(self);peers.forEach((_,u)=>{const x=document.createElement("div");x.className="voice-person";x.innerHTML=`<strong>${esc(cache()[u]?.username||"Member")}</strong><span>Connected</span>`;p.appendChild(x)});const n=peers.size+1;$("voice-count").textContent=n===1?"1 person":`${n} people`}
function panel(){ui();$("voice-panel").hidden=false}
function watchCall(call,started){if(activeCall?.id!==call)return;const unsub=onSnapshot(callRef(call),snap=>{if(!snap.exists()){unsub();leave();return}const d=snap.data();if(d.active!==true||!fresh(d.updatedAt)){unsub();if(activeCall?.id===call)leave()}});activeCall.stopCallWatch=unsub}
function heartbeat(){clearInterval(heartbeat);heartbeat=setInterval(()=>{if(activeCall)updateDoc(callRef(activeCall.id),{updatedAt:serverTimestamp()}).catch(()=>{})},15000)}
async function start(){const c=ctx();if(!c)return;if(activeCall)return toast("You're already in a voice call.");const micOk=await mic().catch(()=>false);if(micOk===false&&!localStream){toast("Microphone permission is required for voice chat.");return}const x=ctx();const ref=callRef(callId(c)),old=await getDoc(ref);if(old.exists()&&old.data().active&&fresh(old.data().updatedAt)){if(c.type==="channel")return join(callId(c),c,old.data());toast("A call is already active here.");return}await setDoc(ref,{kind:c.type,contextId:c.id,name:title(c),members:c.type==="channel"?[]:c.members,active:true,createdBy:id(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});activeCall={id:callId(c),context:c,host:true};await presence(activeCall.id,true);signals(activeCall.id);presenceWatch(activeCall.id);watchCall(activeCall.id);heartbeat();panel();render();if(c.type!=="channel")for(const u of c.members)if(u!==id())await setDoc(invRef(activeCall.id,u),{uid:u,status:"ringing",from:id(),fromName:profile().username||"Someone",createdAt:serverTimestamp()})}
async function join(call,c,data){if(activeCall)return toast("You're already in a voice call.");const d=data||((await getDoc(callRef(call))).data());if(!d||d.active!==true||!fresh(d.updatedAt)){toast("That voice call has ended.");return}const ok=await mic().catch(()=>false);if(ok===false&&!localStream){toast("Microphone permission is required for voice chat.");return}activeCall={id:call,context:c,host:false};await presence(call,true);signals(call);presenceWatch(call);watchCall(call);panel();render()}
async function leave(){if(!activeCall)return;const x=activeCall;for(const p of peers.values())p.close();peers.clear();queuedIce.clear();if(stopSignals)stopSignals();if(stopPresence)stopPresence();if(x.stopCallWatch)x.stopCallWatch();clearInterval(heartbeat);heartbeat=null;await presence(x.id,false);if(x.host)await updateDoc(callRef(x.id),{active:false,endedAt:serverTimestamp(),updatedAt:serverTimestamp()}).catch(()=>{});document.querySelectorAll("audio[data-yv]").forEach(a=>a.remove());stopMic();activeCall=null;$("voice-panel").hidden=true}
function toggleMute(){muted=!muted;localStream?.getAudioTracks().forEach(t=>t.enabled=!muted);$("voice-mute").textContent=muted?"🔇 Unmute":"🎙️ Mute"}
function showIncoming(call,data,invite){if(activeCall||invite.status!=="ringing"||!inviteFresh(invite.createdAt)||!fresh(data.updatedAt))return;incoming={id:call,data};$("voice-title-in").textContent=data.name||"Incoming call";$("voice-sub-in").textContent=`${data.kind==="group"?"Group call":"Direct call"} from ${invite.fromName||cache()[data.createdBy]?.username||"Someone"}`;$("voice-incoming").hidden=false}
async function accept(){if(!incoming)return;const x=incoming;incoming=null;$("voice-incoming").hidden=true;const d=await getDoc(callRef(x.id));if(!d.exists()||!d.data().active||!fresh(d.data().updatedAt)||d.data().createdBy!==x.data.createdBy){toast("That call has ended.");return}await updateDoc(invRef(x.id,id()),{status:"accepted",acceptedAt:serverTimestamp()});await join(x.id,{type:x.data.kind,id:x.data.contextId,name:x.data.name,members:x.data.members||[]},d.data())}
async function decline(){if(!incoming)return;const x=incoming;incoming=null;$("voice-incoming").hidden=true;await updateDoc(invRef(x.id,id()),{status:"declined",declinedAt:serverTimestamp()}).catch(()=>{})}
function invites(){if(stopInvites||!id())return;stopInvites=onSnapshot(query(collection(db(),"voiceCalls"),where("members","array-contains",id()),where("active","==",true)),async snap=>{for(const ch of snap.docChanges()){if(ch.type!=="added"&&ch.type!=="modified")continue;const d=ch.doc.data();if(d.createdBy===id()||activeCall||!fresh(d.updatedAt))continue;const inv=await getDoc(invRef(ch.doc.id,id())).catch(()=>null);if(inv?.exists()&&inv.data().status==="ringing")showIncoming(ch.doc.id,d,inv.data())}})}
function button(){ui();const h=document.getElementById("convo-header");if(!h)return;h.querySelectorAll(".voice-start-btn").forEach(x=>x.remove());const c=ctx();if(!c.currentConvoType)return;const b=document.createElement("button");b.className="voice-start-btn";b.innerHTML=c.currentConvoType==="channel"?"🎙️ <span>Join VC</span>":"📞 <span>Call</span>";b.onclick=async()=>{const x=ctx();const c2=ctx().currentConvoType==="channel"?{type:"channel",id:ctx().currentChannel,name:"#"+ctx().currentChannel,members:[]}:ctx().dmCache?.[ctx().currentDmId]&&{type:ctx().dmCache[ctx().currentDmId].type==="group"?"group":"dm",id:ctx().currentDmId,name:ctx().dmCache[ctx().currentDmId].name||null,members:ctx().dmCache[ctx().currentDmId].members||[]};if(!c2)return;if(c2.type==="channel"){const r=await getDoc(callRef(callId(c2)));if(r.exists()&&r.data().active&&fresh(r.data().updatedAt))await join(callId(c2),c2,r.data());else await start()}else await start()};h.appendChild(b)}
function boot(){style();ui();invites();button();const h=document.getElementById("convo-header");if(h)new MutationObserver(button).observe(h,{childList:true});setInterval(button,5000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();